services:
  db:
    image: mysql:8.0
    container_name: taskflow-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taskflow
      MYSQL_USER: taskflow_user
      MYSQL_PASSWORD: taskflow_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
      - ./logs/mysql:/var/log/mysql
    networks:
      - taskflow-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: ./app
    container_name: taskflow-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: taskflow
      DB_USER: taskflow_user
      DB_PASSWORD: taskflow_password
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      # 👉 важно: app пишет в /app/logs/app.log
      - ./logs/app:/app/logs
    networks:
      - taskflow-network

  web:
    image: nginx:alpine
    container_name: taskflow-web
    restart: always
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
      - ./docs:/usr/share/nginx/html/docs
      - ./logs/nginx:/var/log/nginx
    networks:
      - taskflow-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: taskflow-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - taskflow-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: taskflow-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - taskflow-network

  log-forwarder:
    build:
      context: .
      dockerfile: ./scripts/Dockerfile.forwarder
    container_name: taskflow-forwarder
    depends_on:
      - elasticsearch
    volumes:
      # 👉 теперь 1:1 совпадение с app логами
      - ./logs/app:/logs/app
    networks:
      - taskflow-network

volumes:
  db_data:

networks:
  taskflow-network:
    driver: bridge